# Generated by Django 3.1.3 on 2020-12-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employees',
        ),
    ]
